name: TownyWars
version: 1.1.5
authors: [DanielRHarris]
main: com.danielrharris.townywars.TownyWars
depend: [Towny]
softdepend: [CS-CoreLib, CSCoreLib, BossBarAPI]
commands:
  ideology:
    description: Set your ideology
  townideology:
    description: Check your ideology
  twar:
    usage: No permission!
  twar neutral:
    permission: townywars.neutral
    usage: Syntax error! Perhaps you meant /twar neutral [nation]
  twar repair:
    permission: townywars.repair